#online flow configuration
online:
#The hostname used for the connection with EdgeLock 2GO server.
#It can be obtained from the GUI interface of the EdgeLock 2GO server:
#Admin Settings->Services
  hostname: "https://your-instance.edgelock2go.com"
#The port used for the communication with EdgeLock 2GO server. The
#current value to be used is 443
  port: "EdgeLock 2GO port"
#Indicates if the device will be closed after provisioning.
#Default is no. The device can be closed later using a command
#line argument
  close: 0/1
#indirect flow configuration
indirect:
#partition where the security assets file is located. If the partition is already
#mounted the file is searched within the mount point. If the partition is not
#mounted, the application will mount it.
  partition: "/dev/mmcblk0p1"
#type of partition. Although the partition filesystem type is transparent for
#the application, currently the software that is loading the security assets
#in the partition is supporting only FAT32 partitions.
  type: "vfat"
#in case that the partition is not mounted, it will be mounted in this location
  mount_point: "/run/media/boot-mmcblk0p1"
#the file name containing the security assets in binary format
  file_name: "assets.bin"
#Indicates if the device will be closed after provisioning.
#Default is no. The device can be closed later using a command
#line argument
  close: 0/1

