# ==========================================================================
#                       Provisioning via cloud
# ==========================================================================
online:
# The hostname used for the connection with EdgeLock 2GO server.
# It can be obtained from the GUI interface of the EdgeLock 2GO server:
# Admin Settings->Services
  hostname: "your-instance.edgelock2go.com"

# The port used for the communication with EdgeLock 2GO server. The
# current value to be used is 443
  port: "EdgeLock 2GO port"

# [optional]
# If set to "commit" the non-volatile key storage is committed in the physical
# memory and the hardware anti-rollback counter is incremented after the
# provisioning is done. If the option is not present in the configuration
# file, the key storage is not committed.
# !!! The option has side effects, the key-storage file saved when the
# hardware counter was incremented must be present in the file system
# Uncomment the option if you want to commit the key storage

#  storage: "commit"

# [optional]
# Indicates if the device will be closed after provisioning.
# If the option is missing, the device is not closed. It can be
# later closed using a command line argument
# !!! The action is irreversible and if the device is closed, the device
# will boot signed images only.
# Uncomment the option if you want to change the lifecycle

#  lifecycle: "closed"/"closed-locked"

# [optional]
# The user can optionally provide a custom server certificate used for establishing the TLS
# connection. By default, the EdgeLock 2GO Agent uses its built-in server certificate.
# However, if a different server instance is used (e.g. for testing),
# the user can supply a custom certificate to the OEM Provisioning Application.
# The certificate should be in DER format.

#  server_cert: "server_certificate.der"


# ==========================================================================
# Offline provisioning (provisioning via proxy or product based provisioning)
# ==========================================================================
offline:
# partition where the security assets file is located. If the partition is already
# mounted the file is searched within the mount point. If the partition is not
# mounted, the application will mount it. If the partition is "none", then the
# assets file will be read from the directory indicated by the mount_point in
# the local filesystem.
  partition: "/dev/mmcblk0p1"

# type of partition. Although the partition filesystem type is transparent for
# the application, currently the software that is loading the security assets
# in the partition is supporting only FAT32 partitions.
  type: "vfat"

# in case that the partition is not mounted, it will be mounted in this location.
# in case that the partition is "none", the assets file will be read from this
# directory.
  mount_point: "/run/oem-prov-app"

# the file name containing the security assets in binary format. The field is a list,
# but currently only one assets file is supported.
  file_name: ["assets.bin"]

# [optional]
# If set to "yes" the assets file is deleted after provisioning. If set to "no"
# or missing, the assets file is not deleted after provisioning.

#  delete_assets_file: "yes"/"no"

# [optional]
# If set to "commit" the non-volatile key storage is committed in the physical
# memory and the hardware anti-rollback counter is incremented after the
# provisioning is done. If the option is not present in the configuration
# file, the key storage is not committed.
# !!! The option has side effects, the key-storage file saved when the
# hardware counter was incremented must be present in the file system
# Uncomment the option if you want to commit the key storage

#  storage: "commit"

# [optional]
# Indicates if the device will be closed after provisioning.
# If the option is missing, the device is not closed. It can be
# later closed using a command line argument
# !!! The action is irreversible and if the device is closed, the device
# will boot signed images only.
# Uncomment the option if you want to change the lifecycle

#  lifecycle: "closed"/"closed-locked"

# [optional]
# Indicates the provisioning type. If the option is missing the application
# detects the provisioning type from the blob content. If the option is present
# extra validations can be made (e.g. if the OEM key blob is present for product
# flow provisioning)

#  provisioning: "individual"/"product"

